/* ==================================================================
   CONTENU — VOCABULAIRE NIVEAU A2 (ÉTAPE 3, suite)
   Données pures, même principe que contenu.A1.js. Chargé au premier
   accès par MD.modules.vocabulaire.assurerContenuCharge("A2").

   AVANCEMENT A2 : lot 1 livré (2 thèmes / 14, 170 mots / ~1200).
   Thèmes restants : Université & formation, Travail & collègues,
   Voiture & circulation, Voyages & transports élargis, Banque &
   argent, Administration (bases), Téléphone & Internet, Sport,
   Sorties & vie sociale, Vacances & tourisme, Achats élargis &
   réclamations, Sentiments & caractère — ajoutés dans les lots
   suivants sans toucher à ce fichier.
   ================================================================== */

MD.contenuVocabulaire = MD.contenuVocabulaire || {};

MD.contenuVocabulaire.A2 = [
  {
    id: "routine-quotidienne", label: "Routine quotidienne", icone: "🌅",
    mots: [
      { id: "aufstehen", mot: "aufstehen", pl: "—", fr: "se lever", ex: "Ich stehe um sieben Uhr auf." },
      { id: "waschen-soi", mot: "sich waschen", pl: "—", fr: "se laver", ex: "Ich wasche mich jeden Morgen." },
      { id: "duschen", mot: "sich duschen", pl: "—", fr: "se doucher", ex: "Er duscht sich schnell." },
      { id: "dusche", mot: "die Dusche", pl: "die Duschen", fr: "la douche", ex: "Die Dusche ist warm." },
      { id: "rasieren", mot: "sich rasieren", pl: "—", fr: "se raser", ex: "Mein Vater rasiert sich täglich." },
      { id: "kaemmen", mot: "sich kämmen", pl: "—", fr: "se coiffer", ex: "Sie kämmt sich die Haare." },
      { id: "anziehen-routine", mot: "sich anziehen", pl: "—", fr: "s'habiller", ex: "Ich ziehe mich schnell an." },
      { id: "schminken", mot: "sich schminken", pl: "—", fr: "se maquiller", ex: "Sie schminkt sich vor der Arbeit." },
      { id: "zahnbuerste", mot: "die Zahnbürste", pl: "die Zahnbürsten", fr: "la brosse à dents", ex: "Meine Zahnbürste ist neu." },
      { id: "zahnpasta", mot: "die Zahnpasta", pl: "—", fr: "le dentifrice", ex: "Die Zahnpasta ist fast leer." },
      { id: "zaehne-putzen", mot: "sich die Zähne putzen", pl: "—", fr: "se brosser les dents", ex: "Ich putze mir die Zähne." },
      { id: "shampoo", mot: "das Shampoo", pl: "die Shampoos", fr: "le shampoing", ex: "Das Shampoo riecht gut." },
      { id: "seife", mot: "die Seife", pl: "die Seifen", fr: "le savon", ex: "Die Seife ist im Bad." },
      { id: "wecker", mot: "der Wecker", pl: "die Wecker", fr: "le réveil", ex: "Mein Wecker klingelt um sechs." },
      { id: "klingeln-reveil", mot: "klingeln", pl: "—", fr: "sonner", ex: "Der Wecker klingelt jeden Morgen." },
      { id: "aufwachen-routine", mot: "aufwachen", pl: "—", fr: "se réveiller", ex: "Ich wache müde auf." },
      { id: "tagesablauf", mot: "der Tagesablauf", pl: "die Tagesabläufe", fr: "le déroulement de la journée", ex: "Mein Tagesablauf ist immer gleich." },
      { id: "morgen-moment", mot: "der Morgen", pl: "die Morgen", fr: "le matin", ex: "Am Morgen trinke ich Kaffee." },
      { id: "vormittag", mot: "der Vormittag", pl: "die Vormittage", fr: "la matinée", ex: "Der Vormittag ist ruhig." },
      { id: "mittag", mot: "der Mittag", pl: "die Mittage", fr: "le midi", ex: "Um Mittag esse ich zu Hause." },
      { id: "nachmittag", mot: "der Nachmittag", pl: "die Nachmittage", fr: "l'après-midi", ex: "Am Nachmittag arbeite ich." },
      { id: "abend", mot: "der Abend", pl: "die Abende", fr: "le soir", ex: "Am Abend lese ich gern." },
      { id: "nacht", mot: "die Nacht", pl: "die Nächte", fr: "la nuit", ex: "Die Nacht ist ruhig." },
      { id: "beeilen", mot: "sich beeilen", pl: "—", fr: "se dépêcher", ex: "Ich muss mich beeilen." },
      { id: "puenktlich-routine", mot: "pünktlich", pl: "—", fr: "à l'heure", ex: "Ich komme immer pünktlich." },
      { id: "zu-spaet", mot: "zu spät", pl: "—", fr: "en retard", ex: "Ich bin heute zu spät." },
      { id: "fruehstueck-machen", mot: "das Frühstück machen", pl: "—", fr: "préparer le petit-déjeuner", ex: "Ich mache jeden Morgen Frühstück." },
      { id: "haus-verlassen", mot: "das Haus verlassen", pl: "—", fr: "quitter la maison", ex: "Ich verlasse um acht das Haus." },
      { id: "zur-arbeit-gehen", mot: "zur Arbeit gehen", pl: "—", fr: "aller au travail", ex: "Ich gehe zu Fuß zur Arbeit." },
      { id: "nach-hause-kommen", mot: "nach Hause kommen", pl: "—", fr: "rentrer à la maison", ex: "Ich komme um achtzehn Uhr nach Hause." },
      { id: "feierabend", mot: "der Feierabend", pl: "—", fr: "la fin de journée de travail", ex: "Endlich Feierabend!" },
      { id: "entspannen-routine", mot: "sich entspannen", pl: "—", fr: "se détendre", ex: "Ich entspanne mich abends." },
      { id: "fernsehen-routine", mot: "fernsehen", pl: "—", fr: "regarder la télé", ex: "Wir sehen abends fern." },
      { id: "ins-bett-gehen", mot: "ins Bett gehen", pl: "—", fr: "aller au lit", ex: "Ich gehe um zweiundzwanzig Uhr ins Bett." },
      { id: "einschlafen", mot: "einschlafen", pl: "—", fr: "s'endormir", ex: "Ich schlafe schnell ein." },
      { id: "alltag", mot: "der Alltag", pl: "—", fr: "le quotidien", ex: "Mein Alltag ist stressig." },
      { id: "gewohnheit", mot: "die Gewohnheit", pl: "die Gewohnheiten", fr: "l'habitude", ex: "Das ist eine gute Gewohnheit." },
      { id: "gewoehnlich", mot: "gewöhnlich", pl: "—", fr: "habituellement", ex: "Ich stehe gewöhnlich früh auf." },
      { id: "manchmal", mot: "manchmal", pl: "—", fr: "parfois", ex: "Manchmal schlafe ich lange." },
      { id: "immer", mot: "immer", pl: "—", fr: "toujours", ex: "Ich trinke immer Kaffee." },
      { id: "nie", mot: "nie", pl: "—", fr: "jamais", ex: "Ich rauche nie." },
      { id: "selten", mot: "selten", pl: "—", fr: "rarement", ex: "Ich esse selten Fastfood." },
      { id: "oft", mot: "oft", pl: "—", fr: "souvent", ex: "Ich koche oft zu Hause." },
      { id: "jeden-tag", mot: "jeden Tag", pl: "—", fr: "tous les jours", ex: "Ich lerne jeden Tag Deutsch." },
      { id: "routine", mot: "die Routine", pl: "die Routinen", fr: "la routine", ex: "Meine Routine ist einfach." },
      { id: "zeitplan", mot: "der Zeitplan", pl: "die Zeitpläne", fr: "l'emploi du temps (perso)", ex: "Mein Zeitplan ist voll." },
      { id: "planen", mot: "planen", pl: "—", fr: "planifier", ex: "Ich plane meinen Tag." },
      { id: "verabredung", mot: "die Verabredung", pl: "die Verabredungen", fr: "le rendez-vous (perso)", ex: "Ich habe eine Verabredung um vierzehn Uhr." },
      { id: "sich-verspaeten", mot: "sich verspäten", pl: "—", fr: "être en retard", ex: "Ich habe mich verspätet." },
      { id: "mahlzeit-routine", mot: "die Mahlzeit", pl: "die Mahlzeiten", fr: "le repas", ex: "Wir essen drei Mahlzeiten am Tag." },
      { id: "bett-machen", mot: "das Bett machen", pl: "—", fr: "faire le lit", ex: "Ich mache jeden Morgen das Bett." },
      { id: "aufraeumen-routine", mot: "aufräumen", pl: "—", fr: "ranger", ex: "Ich räume mein Zimmer auf." },
      { id: "pflicht", mot: "die Pflicht", pl: "die Pflichten", fr: "l'obligation", ex: "Das ist meine tägliche Pflicht." },
      { id: "rhythmus", mot: "der Rhythmus", pl: "—", fr: "le rythme (de vie)", ex: "Mein Rhythmus ist stabil." },
      { id: "ausgeruht", mot: "ausgeruht", pl: "—", fr: "reposé", ex: "Ich fühle mich ausgeruht." },
      { id: "erschoepft", mot: "erschöpft", pl: "—", fr: "épuisé", ex: "Am Abend bin ich erschöpft." },
      { id: "entspannt", mot: "entspannt", pl: "—", fr: "détendu", ex: "Am Wochenende bin ich entspannt." },
      { id: "gestresst", mot: "gestresst", pl: "—", fr: "stressé", ex: "Ich bin heute gestresst." },
      { id: "zeit", mot: "die Zeit", pl: "die Zeiten", fr: "le temps (durée)", ex: "Ich habe keine Zeit." },
      { id: "uhrzeit-routine", mot: "die Uhrzeit", pl: "die Uhrzeiten", fr: "l'heure", ex: "Wie ist die Uhrzeit?" },
    ],
  },
  {
    id: "logement-demenagement", label: "Logement & déménagement", icone: "📦",
    mots: [
      { id: "mietvertrag", mot: "der Mietvertrag", pl: "die Mietverträge", fr: "le contrat de location", ex: "Ich unterschreibe den Mietvertrag." },
      { id: "kaution", mot: "die Kaution", pl: "die Kautionen", fr: "la caution", ex: "Die Kaution beträgt zwei Monatsmieten." },
      { id: "nebenkosten", mot: "die Nebenkosten", pl: "—", fr: "les charges (loyer)", ex: "Die Nebenkosten sind hoch." },
      { id: "kuendigung", mot: "die Kündigung", pl: "die Kündigungen", fr: "la résiliation", ex: "Ich schreibe eine Kündigung." },
      { id: "kuendigen", mot: "kündigen", pl: "—", fr: "résilier", ex: "Ich kündige meine Wohnung." },
      { id: "kuendigungsfrist", mot: "die Kündigungsfrist", pl: "die Kündigungsfristen", fr: "le délai de préavis", ex: "Die Kündigungsfrist beträgt drei Monate." },
      { id: "mietspiegel", mot: "der Mietspiegel", pl: "—", fr: "la grille des loyers", ex: "Der Mietspiegel zeigt die Durchschnittspreise." },
      { id: "wohnungsanzeige", mot: "die Wohnungsanzeige", pl: "die Wohnungsanzeigen", fr: "l'annonce de logement", ex: "Ich suche in Wohnungsanzeigen." },
      { id: "besichtigen-logement", mot: "besichtigen", pl: "—", fr: "visiter (un logement)", ex: "Wir besichtigen die Wohnung morgen." },
      { id: "besichtigung", mot: "die Besichtigung", pl: "die Besichtigungen", fr: "la visite (logement)", ex: "Die Besichtigung dauert dreißig Minuten." },
      { id: "makler", mot: "der Makler", pl: "die Makler", fr: "l'agent immobilier", ex: "Der Makler zeigt uns die Wohnung." },
      { id: "maklergebuehr", mot: "die Maklergebühr", pl: "die Maklergebühren", fr: "les frais d'agence", ex: "Die Maklergebühr ist hoch." },
      { id: "moebliert", mot: "möbliert", pl: "—", fr: "meublé", ex: "Die Wohnung ist möbliert." },
      { id: "unmoebliert", mot: "unmöbliert", pl: "—", fr: "non meublé", ex: "Ich suche eine unmöblierte Wohnung." },
      { id: "kaltmiete", mot: "die Kaltmiete", pl: "—", fr: "le loyer hors charges", ex: "Die Kaltmiete beträgt sechshundert Euro." },
      { id: "warmmiete", mot: "die Warmmiete", pl: "—", fr: "le loyer charges comprises", ex: "Die Warmmiete ist höher." },
      { id: "nebenkostenabrechnung", mot: "die Nebenkostenabrechnung", pl: "die Nebenkostenabrechnungen", fr: "le décompte de charges", ex: "Die Nebenkostenabrechnung kommt einmal im Jahr." },
      { id: "hausmeister", mot: "der Hausmeister", pl: "die Hausmeister", fr: "le concierge", ex: "Der Hausmeister repariert die Heizung." },
      { id: "treppenhaus", mot: "das Treppenhaus", pl: "die Treppenhäuser", fr: "la cage d'escalier", ex: "Das Treppenhaus ist sauber." },
      { id: "muelltrennung", mot: "die Mülltrennung", pl: "—", fr: "le tri des déchets", ex: "Die Mülltrennung ist in Deutschland wichtig." },
      { id: "restmuell", mot: "der Restmüll", pl: "—", fr: "les déchets résiduels", ex: "Der Restmüll kommt in die graue Tonne." },
      { id: "biomuell", mot: "der Biomüll", pl: "—", fr: "les biodéchets", ex: "Der Biomüll kommt in die braune Tonne." },
      { id: "altpapier", mot: "das Altpapier", pl: "—", fr: "le papier recyclé", ex: "Das Altpapier kommt in die blaue Tonne." },
      { id: "hausordnung", mot: "die Hausordnung", pl: "die Hausordnungen", fr: "le règlement intérieur", ex: "Die Hausordnung verbietet Lärm nach zweiundzwanzig Uhr." },
      { id: "ruhezeit", mot: "die Ruhezeit", pl: "die Ruhezeiten", fr: "les heures de silence", ex: "Die Ruhezeit beginnt um zweiundzwanzig Uhr." },
      { id: "renovieren-logement", mot: "renovieren", pl: "—", fr: "rénover", ex: "Wir renovieren das Badezimmer." },
      { id: "renovierung", mot: "die Renovierung", pl: "die Renovierungen", fr: "la rénovation", ex: "Die Renovierung dauert zwei Wochen." },
      { id: "streichen", mot: "streichen", pl: "—", fr: "peindre (mur)", ex: "Wir streichen die Wände weiß." },
      { id: "wandfarbe", mot: "die Wandfarbe", pl: "die Wandfarben", fr: "la peinture murale", ex: "Die Wandfarbe ist hellblau." },
      { id: "umzugswagen", mot: "der Umzugswagen", pl: "die Umzugswagen", fr: "le camion de déménagement", ex: "Der Umzugswagen ist gepackt." },
      { id: "umzugsfirma", mot: "die Umzugsfirma", pl: "die Umzugsfirmen", fr: "l'entreprise de déménagement", ex: "Wir engagieren eine Umzugsfirma." },
      { id: "umzugskarton", mot: "der Umzugskarton", pl: "die Umzugskartons", fr: "le carton de déménagement", ex: "Ich packe die Umzugskartons." },
      { id: "einpacken-logement", mot: "einpacken", pl: "—", fr: "emballer (déménagement)", ex: "Ich packe meine Sachen ein." },
      { id: "auspacken", mot: "auspacken", pl: "—", fr: "déballer", ex: "Ich packe die Kartons aus." },
      { id: "tragen-meuble", mot: "tragen", pl: "—", fr: "porter (objet lourd)", ex: "Wir tragen die Möbel zusammen." },
      { id: "moebelpacker", mot: "der Möbelpacker", pl: "die Möbelpacker", fr: "le déménageur", ex: "Die Möbelpacker sind sehr stark." },
      { id: "neue-adresse", mot: "die neue Adresse", pl: "—", fr: "la nouvelle adresse", ex: "Ich gebe meine neue Adresse an." },
      { id: "ummelden", mot: "sich ummelden", pl: "—", fr: "changer d'adresse (officiellement)", ex: "Ich muss mich ummelden." },
      { id: "wohnanmeldung", mot: "die Wohnungsanmeldung", pl: "die Wohnungsanmeldungen", fr: "l'inscription de résidence", ex: "Die Wohnungsanmeldung ist Pflicht." },
      { id: "einwohnermeldeamt", mot: "das Einwohnermeldeamt", pl: "die Einwohnermeldeämter", fr: "le bureau d'enregistrement", ex: "Ich gehe zum Einwohnermeldeamt." },
      { id: "mitbewohner-logement", mot: "der Mitbewohner", pl: "die Mitbewohner", fr: "le colocataire", ex: "Mein Mitbewohner ist sehr nett." },
      { id: "untermiete", mot: "die Untermiete", pl: "—", fr: "la sous-location", ex: "Ich wohne zur Untermiete." },
      { id: "untermieter", mot: "der Untermieter", pl: "die Untermieter", fr: "le sous-locataire", ex: "Der Untermieter zahlt die Hälfte der Miete." },
      { id: "hauptmieter", mot: "der Hauptmieter", pl: "die Hauptmieter", fr: "le locataire principal", ex: "Der Hauptmieter unterschreibt den Vertrag." },
      { id: "kaution-zurueck", mot: "die Kaution zurückerhalten", pl: "—", fr: "récupérer la caution", ex: "Ich erhalte meine Kaution zurück." },
      { id: "schaden", mot: "der Schaden", pl: "die Schäden", fr: "le dommage", ex: "Es gibt einen Schaden an der Wand." },
      { id: "reparieren-logement", mot: "reparieren", pl: "—", fr: "réparer", ex: "Der Vermieter repariert die Heizung." },
      { id: "handwerker", mot: "der Handwerker", pl: "die Handwerker", fr: "l'artisan", ex: "Der Handwerker kommt morgen." },
      { id: "klempner", mot: "der Klempner", pl: "die Klempner", fr: "le plombier", ex: "Der Klempner repariert das Rohr." },
      { id: "elektriker", mot: "der Elektriker", pl: "die Elektriker", fr: "l'électricien", ex: "Der Elektriker prüft die Leitungen." },
      { id: "rohr", mot: "das Rohr", pl: "die Rohre", fr: "le tuyau", ex: "Das Rohr ist kaputt." },
      { id: "undicht", mot: "undicht", pl: "—", fr: "qui fuit", ex: "Der Wasserhahn ist undicht." },
      { id: "wasserhahn", mot: "der Wasserhahn", pl: "die Wasserhähne", fr: "le robinet", ex: "Der Wasserhahn tropft." },
      { id: "stromausfall", mot: "der Stromausfall", pl: "die Stromausfälle", fr: "la panne de courant", ex: "Es gab einen Stromausfall." },
      { id: "kontaktieren", mot: "kontaktieren", pl: "—", fr: "contacter", ex: "Ich kontaktiere den Vermieter." },
      { id: "beschwerde-logement", mot: "die Beschwerde", pl: "die Beschwerden", fr: "la plainte", ex: "Ich habe eine Beschwerde eingereicht." },
      { id: "sich-beschweren", mot: "sich beschweren", pl: "—", fr: "se plaindre", ex: "Ich beschwere mich über den Lärm." },
      { id: "laerm", mot: "der Lärm", pl: "—", fr: "le bruit", ex: "Der Lärm ist unerträglich." },
      { id: "leise", mot: "leise", pl: "—", fr: "silencieux", ex: "Bitte sei leise." },
      { id: "wohnflaeche", mot: "die Wohnfläche", pl: "—", fr: "la surface habitable", ex: "Die Wohnfläche beträgt sechzig Quadratmeter." },
      { id: "quadratmeter", mot: "der Quadratmeter", pl: "die Quadratmeter", fr: "le mètre carré", ex: "Die Wohnung hat fünfzig Quadratmeter." },
      { id: "grundriss", mot: "der Grundriss", pl: "die Grundrisse", fr: "le plan (logement)", ex: "Der Grundriss ist praktisch." },
      { id: "wohngegend", mot: "die Wohngegend", pl: "die Wohngegenden", fr: "le quartier résidentiel", ex: "Die Wohngegend ist ruhig." },
      { id: "zentral-gelegen", mot: "zentral gelegen", pl: "—", fr: "bien situé", ex: "Die Wohnung ist zentral gelegen." },
      { id: "anbindung", mot: "die Anbindung", pl: "—", fr: "la desserte (transports)", ex: "Die Anbindung ist ausgezeichnet." },
      { id: "eigentumswohnung", mot: "die Eigentumswohnung", pl: "die Eigentumswohnungen", fr: "l'appartement en propriété", ex: "Sie kauft eine Eigentumswohnung." },
      { id: "eigentuemer", mot: "der Eigentümer", pl: "die Eigentümer", fr: "le propriétaire (bien)", ex: "Der Eigentümer wohnt im Ausland." },
      { id: "besitzen", mot: "besitzen", pl: "—", fr: "posséder", ex: "Er besitzt zwei Wohnungen." },
      { id: "kredit", mot: "der Kredit", pl: "die Kredite", fr: "le crédit (prêt)", ex: "Wir nehmen einen Kredit auf." },
      { id: "hypothek", mot: "die Hypothek", pl: "die Hypotheken", fr: "l'hypothèque", ex: "Die Hypothek läuft über zwanzig Jahre." },
      { id: "abbezahlen", mot: "abbezahlen", pl: "—", fr: "rembourser", ex: "Wir bezahlen den Kredit ab." },
      { id: "rate", mot: "die Rate", pl: "die Raten", fr: "la mensualité", ex: "Die monatliche Rate ist hoch." },
      { id: "sich-einleben", mot: "sich einleben", pl: "—", fr: "s'installer (s'habituer)", ex: "Ich lebe mich langsam ein." },
      { id: "sich-wohlfuehlen", mot: "sich wohlfühlen", pl: "—", fr: "se sentir bien (chez soi)", ex: "Ich fühle mich hier wohl." },
      { id: "waermedaemmung", mot: "die Wärmedämmung", pl: "—", fr: "l'isolation thermique", ex: "Die Wärmedämmung ist gut." },
      { id: "energieeffizient", mot: "energieeffizient", pl: "—", fr: "économe en énergie", ex: "Die Wohnung ist energieeffizient." },
      { id: "energieausweis", mot: "der Energieausweis", pl: "die Energieausweise", fr: "le certificat énergétique", ex: "Der Vermieter zeigt den Energieausweis." },
      { id: "balkon-logement", mot: "der Balkon", pl: "die Balkone", fr: "le balcon", ex: "Der Balkon ist nach Süden ausgerichtet." },
      { id: "terrasse", mot: "die Terrasse", pl: "die Terrassen", fr: "la terrasse", ex: "Die Terrasse ist groß." },
      { id: "dachboden", mot: "der Dachboden", pl: "die Dachböden", fr: "le grenier", ex: "Wir lagern Kisten auf dem Dachboden." },
      { id: "abstellkammer", mot: "die Abstellkammer", pl: "die Abstellkammern", fr: "le débarras", ex: "Die Abstellkammer ist voll." },
      { id: "barrierefrei", mot: "barrierefrei", pl: "—", fr: "accessible (sans obstacle)", ex: "Die Wohnung ist barrierefrei." },
      { id: "wohnungssuche", mot: "die Wohnungssuche", pl: "—", fr: "la recherche de logement", ex: "Die Wohnungssuche ist schwierig." },
      { id: "verfuegbar", mot: "verfügbar", pl: "—", fr: "disponible", ex: "Die Wohnung ist ab sofort verfügbar." },
      { id: "einzug", mot: "der Einzug", pl: "die Einzüge", fr: "l'emménagement", ex: "Der Einzug ist am ersten Mai." },
      { id: "einziehen", mot: "einziehen", pl: "—", fr: "emménager", ex: "Wir ziehen nächste Woche ein." },
      { id: "ausziehen-logement", mot: "ausziehen", pl: "—", fr: "déménager (quitter)", ex: "Ich ziehe Ende des Monats aus." },
      { id: "auszug", mot: "der Auszug", pl: "die Auszüge", fr: "le déménagement (départ)", ex: "Der Auszug ist stressig." },
      { id: "uebergabe", mot: "die Übergabe", pl: "die Übergaben", fr: "la remise des clés", ex: "Die Übergabe findet am Montag statt." },
      { id: "protokoll", mot: "das Protokoll", pl: "die Protokolle", fr: "le procès-verbal (état des lieux)", ex: "Wir unterschreiben das Protokoll." },
      { id: "zustand", mot: "der Zustand", pl: "die Zustände", fr: "l'état (d'un logement)", ex: "Die Wohnung ist in gutem Zustand." },
      { id: "abnahme", mot: "die Abnahme", pl: "die Abnahmen", fr: "la réception (état des lieux)", ex: "Die Abnahme der Wohnung ist morgen." },
      { id: "zaehler", mot: "der Zähler", pl: "die Zähler", fr: "le compteur", ex: "Der Zähler zeigt den Verbrauch." },
      { id: "verbrauch", mot: "der Verbrauch", pl: "—", fr: "la consommation", ex: "Der Verbrauch ist hoch." },
      { id: "ablesen", mot: "ablesen", pl: "—", fr: "relever (un compteur)", ex: "Der Techniker liest den Zähler ab." },
      { id: "zeuge", mot: "der Zeuge", pl: "die Zeugen", fr: "le témoin", ex: "Wir brauchen einen Zeugen für den Vertrag." },
      { id: "unterschreiben-logement", mot: "unterschreiben", pl: "—", fr: "signer", ex: "Wir unterschreiben den Mietvertrag." },
      { id: "klausel", mot: "die Klausel", pl: "die Klauseln", fr: "la clause", ex: "Diese Klausel ist wichtig." },
      { id: "absatz", mot: "der Absatz", pl: "die Absätze", fr: "le paragraphe (contrat)", ex: "Lesen Sie den Absatz sorgfältig." },
      { id: "bedingung", mot: "die Bedingung", pl: "die Bedingungen", fr: "la condition (contrat)", ex: "Die Bedingungen sind klar." },
      { id: "akzeptieren", mot: "akzeptieren", pl: "—", fr: "accepter", ex: "Ich akzeptiere die Bedingungen." },
      { id: "ablehnen", mot: "ablehnen", pl: "—", fr: "refuser", ex: "Der Vermieter lehnt den Antrag ab." },
      { id: "antrag-logement", mot: "der Antrag", pl: "die Anträge", fr: "la demande", ex: "Ich stelle einen Antrag auf Wohngeld." },
      { id: "wohngeld", mot: "das Wohngeld", pl: "—", fr: "l'allocation logement", ex: "Ich beantrage Wohngeld." },
      { id: "sozialwohnung", mot: "die Sozialwohnung", pl: "die Sozialwohnungen", fr: "le logement social", ex: "Sie wohnt in einer Sozialwohnung." },
      { id: "gemeinsam", mot: "gemeinsam", pl: "—", fr: "ensemble (partagé)", ex: "Wir teilen die Wohnung gemeinsam." },
      { id: "teilen", mot: "teilen", pl: "—", fr: "partager", ex: "Wir teilen die Miete." },
      { id: "wg-zimmer", mot: "das WG-Zimmer", pl: "die WG-Zimmer", fr: "la chambre en colocation", ex: "Ich suche ein WG-Zimmer." },
      { id: "umzugstermin", mot: "der Umzugstermin", pl: "die Umzugstermine", fr: "la date de déménagement", ex: "Der Umzugstermin steht fest." },
      { id: "sich-niederlassen", mot: "sich niederlassen", pl: "—", fr: "s'installer (définitivement)", ex: "Wir lassen uns hier nieder." },
    ],
  },
];
