/* ==================================================================
   CONTENU — VOCABULAIRE NIVEAU A2 (ÉTAPE 3, suite)
   Données pures, même principe que contenu.A1.js. Chargé au premier
   accès par MD.modules.vocabulaire.assurerContenuCharge("A2").

   AVANCEMENT A2 : lot 1 livré (2 thèmes / 14, 170 mots / ~1200).
   Thèmes restants : Université & formation, Travail & collègues,
   Voiture & circulation, Voyages & transports élargis, Banque &
   argent, Administration (bases), Téléphone & Internet, Sport,
   Sorties & vie sociale, Vacances & tourisme, Achats élargis &
   réclamations, Sentiments & caractère — ajoutés dans les lots
   suivants sans toucher à ce fichier.
   ================================================================== */

MD.contenuVocabulaire = MD.contenuVocabulaire || {};

MD.contenuVocabulaire.A2 = [
  {
    id: "routine-quotidienne", label: "Routine quotidienne", icone: "🌅",
    mots: [
      { id: "aufstehen", mot: "aufstehen", pl: "—", fr: "se lever", ex: "Ich stehe um sieben Uhr auf." },
      { id: "waschen-soi", mot: "sich waschen", pl: "—", fr: "se laver", ex: "Ich wasche mich jeden Morgen." },
      { id: "duschen", mot: "sich duschen", pl: "—", fr: "se doucher", ex: "Er duscht sich schnell." },
      { id: "dusche", mot: "die Dusche", pl: "die Duschen", fr: "la douche", ex: "Die Dusche ist warm." },
      { id: "rasieren", mot: "sich rasieren", pl: "—", fr: "se raser", ex: "Mein Vater rasiert sich täglich." },
      { id: "kaemmen", mot: "sich kämmen", pl: "—", fr: "se coiffer", ex: "Sie kämmt sich die Haare." },
      { id: "anziehen-routine", mot: "sich anziehen", pl: "—", fr: "s'habiller", ex: "Ich ziehe mich schnell an." },
      { id: "schminken", mot: "sich schminken", pl: "—", fr: "se maquiller", ex: "Sie schminkt sich vor der Arbeit." },
      { id: "zahnbuerste", mot: "die Zahnbürste", pl: "die Zahnbürsten", fr: "la brosse à dents", ex: "Meine Zahnbürste ist neu." },
      { id: "zahnpasta", mot: "die Zahnpasta", pl: "—", fr: "le dentifrice", ex: "Die Zahnpasta ist fast leer." },
      { id: "zaehne-putzen", mot: "sich die Zähne putzen", pl: "—", fr: "se brosser les dents", ex: "Ich putze mir die Zähne." },
      { id: "shampoo", mot: "das Shampoo", pl: "die Shampoos", fr: "le shampoing", ex: "Das Shampoo riecht gut." },
      { id: "seife", mot: "die Seife", pl: "die Seifen", fr: "le savon", ex: "Die Seife ist im Bad." },
      { id: "wecker", mot: "der Wecker", pl: "die Wecker", fr: "le réveil", ex: "Mein Wecker klingelt um sechs." },
      { id: "klingeln-reveil", mot: "klingeln", pl: "—", fr: "sonner", ex: "Der Wecker klingelt jeden Morgen." },
      { id: "aufwachen-routine", mot: "aufwachen", pl: "—", fr: "se réveiller", ex: "Ich wache müde auf." },
      { id: "tagesablauf", mot: "der Tagesablauf", pl: "die Tagesabläufe", fr: "le déroulement de la journée", ex: "Mein Tagesablauf ist immer gleich." },
      { id: "morgen-moment", mot: "der Morgen", pl: "die Morgen", fr: "le matin", ex: "Am Morgen trinke ich Kaffee." },
      { id: "vormittag", mot: "der Vormittag", pl: "die Vormittage", fr: "la matinée", ex: "Der Vormittag ist ruhig." },
      { id: "mittag", mot: "der Mittag", pl: "die Mittage", fr: "le midi", ex: "Um Mittag esse ich zu Hause." },
      { id: "nachmittag", mot: "der Nachmittag", pl: "die Nachmittage", fr: "l'après-midi", ex: "Am Nachmittag arbeite ich." },
      { id: "abend", mot: "der Abend", pl: "die Abende", fr: "le soir", ex: "Am Abend lese ich gern." },
      { id: "nacht", mot: "die Nacht", pl: "die Nächte", fr: "la nuit", ex: "Die Nacht ist ruhig." },
      { id: "beeilen", mot: "sich beeilen", pl: "—", fr: "se dépêcher", ex: "Ich muss mich beeilen." },
      { id: "puenktlich-routine", mot: "pünktlich", pl: "—", fr: "à l'heure", ex: "Ich komme immer pünktlich." },
      { id: "zu-spaet", mot: "zu spät", pl: "—", fr: "en retard", ex: "Ich bin heute zu spät." },
      { id: "fruehstueck-machen", mot: "das Frühstück machen", pl: "—", fr: "préparer le petit-déjeuner", ex: "Ich mache jeden Morgen Frühstück." },
      { id: "haus-verlassen", mot: "das Haus verlassen", pl: "—", fr: "quitter la maison", ex: "Ich verlasse um acht das Haus." },
      { id: "zur-arbeit-gehen", mot: "zur Arbeit gehen", pl: "—", fr: "aller au travail", ex: "Ich gehe zu Fuß zur Arbeit." },
      { id: "nach-hause-kommen", mot: "nach Hause kommen", pl: "—", fr: "rentrer à la maison", ex: "Ich komme um achtzehn Uhr nach Hause." },
      { id: "feierabend", mot: "der Feierabend", pl: "—", fr: "la fin de journée de travail", ex: "Endlich Feierabend!" },
      { id: "entspannen-routine", mot: "sich entspannen", pl: "—", fr: "se détendre", ex: "Ich entspanne mich abends." },
      { id: "fernsehen-routine", mot: "fernsehen", pl: "—", fr: "regarder la télé", ex: "Wir sehen abends fern." },
      { id: "ins-bett-gehen", mot: "ins Bett gehen", pl: "—", fr: "aller au lit", ex: "Ich gehe um zweiundzwanzig Uhr ins Bett." },
      { id: "einschlafen", mot: "einschlafen", pl: "—", fr: "s'endormir", ex: "Ich schlafe schnell ein." },
      { id: "alltag", mot: "der Alltag", pl: "—", fr: "le quotidien", ex: "Mein Alltag ist stressig." },
      { id: "gewohnheit", mot: "die Gewohnheit", pl: "die Gewohnheiten", fr: "l'habitude", ex: "Das ist eine gute Gewohnheit." },
      { id: "gewoehnlich", mot: "gewöhnlich", pl: "—", fr: "habituellement", ex: "Ich stehe gewöhnlich früh auf." },
      { id: "manchmal", mot: "manchmal", pl: "—", fr: "parfois", ex: "Manchmal schlafe ich lange." },
      { id: "immer", mot: "immer", pl: "—", fr: "toujours", ex: "Ich trinke immer Kaffee." },
      { id: "nie", mot: "nie", pl: "—", fr: "jamais", ex: "Ich rauche nie." },
      { id: "selten", mot: "selten", pl: "—", fr: "rarement", ex: "Ich esse selten Fastfood." },
      { id: "oft", mot: "oft", pl: "—", fr: "souvent", ex: "Ich koche oft zu Hause." },
      { id: "jeden-tag", mot: "jeden Tag", pl: "—", fr: "tous les jours", ex: "Ich lerne jeden Tag Deutsch." },
      { id: "routine", mot: "die Routine", pl: "die Routinen", fr: "la routine", ex: "Meine Routine ist einfach." },
      { id: "zeitplan", mot: "der Zeitplan", pl: "die Zeitpläne", fr: "l'emploi du temps (perso)", ex: "Mein Zeitplan ist voll." },
      { id: "planen", mot: "planen", pl: "—", fr: "planifier", ex: "Ich plane meinen Tag." },
      { id: "verabredung", mot: "die Verabredung", pl: "die Verabredungen", fr: "le rendez-vous (perso)", ex: "Ich habe eine Verabredung um vierzehn Uhr." },
      { id: "sich-verspaeten", mot: "sich verspäten", pl: "—", fr: "être en retard", ex: "Ich habe mich verspätet." },
      { id: "mahlzeit-routine", mot: "die Mahlzeit", pl: "die Mahlzeiten", fr: "le repas", ex: "Wir essen drei Mahlzeiten am Tag." },
      { id: "bett-machen", mot: "das Bett machen", pl: "—", fr: "faire le lit", ex: "Ich mache jeden Morgen das Bett." },
      { id: "aufraeumen-routine", mot: "aufräumen", pl: "—", fr: "ranger", ex: "Ich räume mein Zimmer auf." },
      { id: "pflicht", mot: "die Pflicht", pl: "die Pflichten", fr: "l'obligation", ex: "Das ist meine tägliche Pflicht." },
      { id: "rhythmus", mot: "der Rhythmus", pl: "—", fr: "le rythme (de vie)", ex: "Mein Rhythmus ist stabil." },
      { id: "ausgeruht", mot: "ausgeruht", pl: "—", fr: "reposé", ex: "Ich fühle mich ausgeruht." },
      { id: "erschoepft", mot: "erschöpft", pl: "—", fr: "épuisé", ex: "Am Abend bin ich erschöpft." },
      { id: "entspannt", mot: "entspannt", pl: "—", fr: "détendu", ex: "Am Wochenende bin ich entspannt." },
      { id: "gestresst", mot: "gestresst", pl: "—", fr: "stressé", ex: "Ich bin heute gestresst." },
      { id: "zeit", mot: "die Zeit", pl: "die Zeiten", fr: "le temps (durée)", ex: "Ich habe keine Zeit." },
      { id: "uhrzeit-routine", mot: "die Uhrzeit", pl: "die Uhrzeiten", fr: "l'heure", ex: "Wie ist die Uhrzeit?" },
    ],
  },
  {
    id: "logement-demenagement", label: "Logement & déménagement", icone: "📦",
    mots: [
      { id: "mietvertrag", mot: "der Mietvertrag", pl: "die Mietverträge", fr: "le contrat de location", ex: "Ich unterschreibe den Mietvertrag." },
      { id: "kaution", mot: "die Kaution", pl: "die Kautionen", fr: "la caution", ex: "Die Kaution beträgt zwei Monatsmieten." },
      { id: "nebenkosten", mot: "die Nebenkosten", pl: "—", fr: "les charges (loyer)", ex: "Die Nebenkosten sind hoch." },
      { id: "kuendigung", mot: "die Kündigung", pl: "die Kündigungen", fr: "la résiliation", ex: "Ich schreibe eine Kündigung." },
      { id: "kuendigen", mot: "kündigen", pl: "—", fr: "résilier", ex: "Ich kündige meine Wohnung." },
      { id: "kuendigungsfrist", mot: "die Kündigungsfrist", pl: "die Kündigungsfristen", fr: "le délai de préavis", ex: "Die Kündigungsfrist beträgt drei Monate." },
      { id: "mietspiegel", mot: "der Mietspiegel", pl: "—", fr: "la grille des loyers", ex: "Der Mietspiegel zeigt die Durchschnittspreise." },
      { id: "wohnungsanzeige", mot: "die Wohnungsanzeige", pl: "die Wohnungsanzeigen", fr: "l'annonce de logement", ex: "Ich suche in Wohnungsanzeigen." },
      { id: "besichtigen-logement", mot: "besichtigen", pl: "—", fr: "visiter (un logement)", ex: "Wir besichtigen die Wohnung morgen." },
      { id: "besichtigung", mot: "die Besichtigung", pl: "die Besichtigungen", fr: "la visite (logement)", ex: "Die Besichtigung dauert dreißig Minuten." },
      { id: "makler", mot: "der Makler", pl: "die Makler", fr: "l'agent immobilier", ex: "Der Makler zeigt uns die Wohnung." },
      { id: "maklergebuehr", mot: "die Maklergebühr", pl: "die Maklergebühren", fr: "les frais d'agence", ex: "Die Maklergebühr ist hoch." },
      { id: "moebliert", mot: "möbliert", pl: "—", fr: "meublé", ex: "Die Wohnung ist möbliert." },
      { id: "unmoebliert", mot: "unmöbliert", pl: "—", fr: "non meublé", ex: "Ich suche eine unmöblierte Wohnung." },
      { id: "kaltmiete", mot: "die Kaltmiete", pl: "—", fr: "le loyer hors charges", ex: "Die Kaltmiete beträgt sechshundert Euro." },
      { id: "warmmiete", mot: "die Warmmiete", pl: "—", fr: "le loyer charges comprises", ex: "Die Warmmiete ist höher." },
      { id: "nebenkostenabrechnung", mot: "die Nebenkostenabrechnung", pl: "die Nebenkostenabrechnungen", fr: "le décompte de charges", ex: "Die Nebenkostenabrechnung kommt einmal im Jahr." },
      { id: "hausmeister", mot: "der Hausmeister", pl: "die Hausmeister", fr: "le concierge", ex: "Der Hausmeister repariert die Heizung." },
      { id: "treppenhaus", mot: "das Treppenhaus", pl: "die Treppenhäuser", fr: "la cage d'escalier", ex: "Das Treppenhaus ist sauber." },
      { id: "muelltrennung", mot: "die Mülltrennung", pl: "—", fr: "le tri des déchets", ex: "Die Mülltrennung ist in Deutschland wichtig." },
      { id: "restmuell", mot: "der Restmüll", pl: "—", fr: "les déchets résiduels", ex: "Der Restmüll kommt in die graue Tonne." },
      { id: "biomuell", mot: "der Biomüll", pl: "—", fr: "les biodéchets", ex: "Der Biomüll kommt in die braune Tonne." },
      { id: "altpapier", mot: "das Altpapier", pl: "—", fr: "le papier recyclé", ex: "Das Altpapier kommt in die blaue Tonne." },
      { id: "hausordnung", mot: "die Hausordnung", pl: "die Hausordnungen", fr: "le règlement intérieur", ex: "Die Hausordnung verbietet Lärm nach zweiundzwanzig Uhr." },
      { id: "ruhezeit", mot: "die Ruhezeit", pl: "die Ruhezeiten", fr: "les heures de silence", ex: "Die Ruhezeit beginnt um zweiundzwanzig Uhr." },
      { id: "renovieren-logement", mot: "renovieren", pl: "—", fr: "rénover", ex: "Wir renovieren das Badezimmer." },
      { id: "renovierung", mot: "die Renovierung", pl: "die Renovierungen", fr: "la rénovation", ex: "Die Renovierung dauert zwei Wochen." },
      { id: "streichen", mot: "streichen", pl: "—", fr: "peindre (mur)", ex: "Wir streichen die Wände weiß." },
      { id: "wandfarbe", mot: "die Wandfarbe", pl: "die Wandfarben", fr: "la peinture murale", ex: "Die Wandfarbe ist hellblau." },
      { id: "umzugswagen", mot: "der Umzugswagen", pl: "die Umzugswagen", fr: "le camion de déménagement", ex: "Der Umzugswagen ist gepackt." },
      { id: "umzugsfirma", mot: "die Umzugsfirma", pl: "die Umzugsfirmen", fr: "l'entreprise de déménagement", ex: "Wir engagieren eine Umzugsfirma." },
      { id: "umzugskarton", mot: "der Umzugskarton", pl: "die Umzugskartons", fr: "le carton de déménagement", ex: "Ich packe die Umzugskartons." },
      { id: "einpacken-logement", mot: "einpacken", pl: "—", fr: "emballer (déménagement)", ex: "Ich packe meine Sachen ein." },
      { id: "auspacken", mot: "auspacken", pl: "—", fr: "déballer", ex: "Ich packe die Kartons aus." },
      { id: "tragen-meuble", mot: "tragen", pl: "—", fr: "porter (objet lourd)", ex: "Wir tragen die Möbel zusammen." },
      { id: "moebelpacker", mot: "der Möbelpacker", pl: "die Möbelpacker", fr: "le déménageur", ex: "Die Möbelpacker sind sehr stark." },
      { id: "neue-adresse", mot: "die neue Adresse", pl: "—", fr: "la nouvelle adresse", ex: "Ich gebe meine neue Adresse an." },
      { id: "ummelden", mot: "sich ummelden", pl: "—", fr: "changer d'adresse (officiellement)", ex: "Ich muss mich ummelden." },
      { id: "wohnanmeldung", mot: "die Wohnungsanmeldung", pl: "die Wohnungsanmeldungen", fr: "l'inscription de résidence", ex: "Die Wohnungsanmeldung ist Pflicht." },
      { id: "einwohnermeldeamt", mot: "das Einwohnermeldeamt", pl: "die Einwohnermeldeämter", fr: "le bureau d'enregistrement", ex: "Ich gehe zum Einwohnermeldeamt." },
      { id: "mitbewohner-logement", mot: "der Mitbewohner", pl: "die Mitbewohner", fr: "le colocataire", ex: "Mein Mitbewohner ist sehr nett." },
      { id: "untermiete", mot: "die Untermiete", pl: "—", fr: "la sous-location", ex: "Ich wohne zur Untermiete." },
      { id: "untermieter", mot: "der Untermieter", pl: "die Untermieter", fr: "le sous-locataire", ex: "Der Untermieter zahlt die Hälfte der Miete." },
      { id: "hauptmieter", mot: "der Hauptmieter", pl: "die Hauptmieter", fr: "le locataire principal", ex: "Der Hauptmieter unterschreibt den Vertrag." },
      { id: "kaution-zurueck", mot: "die Kaution zurückerhalten", pl: "—", fr: "récupérer la caution", ex: "Ich erhalte meine Kaution zurück." },
      { id: "schaden", mot: "der Schaden", pl: "die Schäden", fr: "le dommage", ex: "Es gibt einen Schaden an der Wand." },
      { id: "reparieren-logement", mot: "reparieren", pl: "—", fr: "réparer", ex: "Der Vermieter repariert die Heizung." },
      { id: "handwerker", mot: "der Handwerker", pl: "die Handwerker", fr: "l'artisan", ex: "Der Handwerker kommt morgen." },
      { id: "klempner", mot: "der Klempner", pl: "die Klempner", fr: "le plombier", ex: "Der Klempner repariert das Rohr." },
      { id: "elektriker", mot: "der Elektriker", pl: "die Elektriker", fr: "l'électricien", ex: "Der Elektriker prüft die Leitungen." },
      { id: "rohr", mot: "das Rohr", pl: "die Rohre", fr: "le tuyau", ex: "Das Rohr ist kaputt." },
      { id: "undicht", mot: "undicht", pl: "—", fr: "qui fuit", ex: "Der Wasserhahn ist undicht." },
      { id: "wasserhahn", mot: "der Wasserhahn", pl: "die Wasserhähne", fr: "le robinet", ex: "Der Wasserhahn tropft." },
      { id: "stromausfall", mot: "der Stromausfall", pl: "die Stromausfälle", fr: "la panne de courant", ex: "Es gab einen Stromausfall." },
      { id: "kontaktieren", mot: "kontaktieren", pl: "—", fr: "contacter", ex: "Ich kontaktiere den Vermieter." },
      { id: "beschwerde-logement", mot: "die Beschwerde", pl: "die Beschwerden", fr: "la plainte", ex: "Ich habe eine Beschwerde eingereicht." },
      { id: "sich-beschweren", mot: "sich beschweren", pl: "—", fr: "se plaindre", ex: "Ich beschwere mich über den Lärm." },
      { id: "laerm", mot: "der Lärm", pl: "—", fr: "le bruit", ex: "Der Lärm ist unerträglich." },
      { id: "leise", mot: "leise", pl: "—", fr: "silencieux", ex: "Bitte sei leise." },
      { id: "wohnflaeche", mot: "die Wohnfläche", pl: "—", fr: "la surface habitable", ex: "Die Wohnfläche beträgt sechzig Quadratmeter." },
      { id: "quadratmeter", mot: "der Quadratmeter", pl: "die Quadratmeter", fr: "le mètre carré", ex: "Die Wohnung hat fünfzig Quadratmeter." },
      { id: "grundriss", mot: "der Grundriss", pl: "die Grundrisse", fr: "le plan (logement)", ex: "Der Grundriss ist praktisch." },
      { id: "wohngegend", mot: "die Wohngegend", pl: "die Wohngegenden", fr: "le quartier résidentiel", ex: "Die Wohngegend ist ruhig." },
      { id: "zentral-gelegen", mot: "zentral gelegen", pl: "—", fr: "bien situé", ex: "Die Wohnung ist zentral gelegen." },
      { id: "anbindung", mot: "die Anbindung", pl: "—", fr: "la desserte (transports)", ex: "Die Anbindung ist ausgezeichnet." },
      { id: "eigentumswohnung", mot: "die Eigentumswohnung", pl: "die Eigentumswohnungen", fr: "l'appartement en propriété", ex: "Sie kauft eine Eigentumswohnung." },
      { id: "eigentuemer", mot: "der Eigentümer", pl: "die Eigentümer", fr: "le propriétaire (bien)", ex: "Der Eigentümer wohnt im Ausland." },
      { id: "besitzen", mot: "besitzen", pl: "—", fr: "posséder", ex: "Er besitzt zwei Wohnungen." },
      { id: "kredit", mot: "der Kredit", pl: "die Kredite", fr: "le crédit (prêt)", ex: "Wir nehmen einen Kredit auf." },
      { id: "hypothek", mot: "die Hypothek", pl: "die Hypotheken", fr: "l'hypothèque", ex: "Die Hypothek läuft über zwanzig Jahre." },
      { id: "abbezahlen", mot: "abbezahlen", pl: "—", fr: "rembourser", ex: "Wir bezahlen den Kredit ab." },
      { id: "rate", mot: "die Rate", pl: "die Raten", fr: "la mensualité", ex: "Die monatliche Rate ist hoch." },
      { id: "sich-einleben", mot: "sich einleben", pl: "—", fr: "s'installer (s'habituer)", ex: "Ich lebe mich langsam ein." },
      { id: "sich-wohlfuehlen", mot: "sich wohlfühlen", pl: "—", fr: "se sentir bien (chez soi)", ex: "Ich fühle mich hier wohl." },
      { id: "waermedaemmung", mot: "die Wärmedämmung", pl: "—", fr: "l'isolation thermique", ex: "Die Wärmedämmung ist gut." },
      { id: "energieeffizient", mot: "energieeffizient", pl: "—", fr: "économe en énergie", ex: "Die Wohnung ist energieeffizient." },
      { id: "energieausweis", mot: "der Energieausweis", pl: "die Energieausweise", fr: "le certificat énergétique", ex: "Der Vermieter zeigt den Energieausweis." },
      { id: "balkon-logement", mot: "der Balkon", pl: "die Balkone", fr: "le balcon", ex: "Der Balkon ist nach Süden ausgerichtet." },
      { id: "terrasse", mot: "die Terrasse", pl: "die Terrassen", fr: "la terrasse", ex: "Die Terrasse ist groß." },
      { id: "dachboden", mot: "der Dachboden", pl: "die Dachböden", fr: "le grenier", ex: "Wir lagern Kisten auf dem Dachboden." },
      { id: "abstellkammer", mot: "die Abstellkammer", pl: "die Abstellkammern", fr: "le débarras", ex: "Die Abstellkammer ist voll." },
      { id: "barrierefrei", mot: "barrierefrei", pl: "—", fr: "accessible (sans obstacle)", ex: "Die Wohnung ist barrierefrei." },
      { id: "wohnungssuche", mot: "die Wohnungssuche", pl: "—", fr: "la recherche de logement", ex: "Die Wohnungssuche ist schwierig." },
      { id: "verfuegbar", mot: "verfügbar", pl: "—", fr: "disponible", ex: "Die Wohnung ist ab sofort verfügbar." },
      { id: "einzug", mot: "der Einzug", pl: "die Einzüge", fr: "l'emménagement", ex: "Der Einzug ist am ersten Mai." },
      { id: "einziehen", mot: "einziehen", pl: "—", fr: "emménager", ex: "Wir ziehen nächste Woche ein." },
      { id: "ausziehen-logement", mot: "ausziehen", pl: "—", fr: "déménager (quitter)", ex: "Ich ziehe Ende des Monats aus." },
      { id: "auszug", mot: "der Auszug", pl: "die Auszüge", fr: "le déménagement (départ)", ex: "Der Auszug ist stressig." },
      { id: "uebergabe", mot: "die Übergabe", pl: "die Übergaben", fr: "la remise des clés", ex: "Die Übergabe findet am Montag statt." },
      { id: "protokoll", mot: "das Protokoll", pl: "die Protokolle", fr: "le procès-verbal (état des lieux)", ex: "Wir unterschreiben das Protokoll." },
      { id: "zustand", mot: "der Zustand", pl: "die Zustände", fr: "l'état (d'un logement)", ex: "Die Wohnung ist in gutem Zustand." },
      { id: "abnahme", mot: "die Abnahme", pl: "die Abnahmen", fr: "la réception (état des lieux)", ex: "Die Abnahme der Wohnung ist morgen." },
      { id: "zaehler", mot: "der Zähler", pl: "die Zähler", fr: "le compteur", ex: "Der Zähler zeigt den Verbrauch." },
      { id: "verbrauch", mot: "der Verbrauch", pl: "—", fr: "la consommation", ex: "Der Verbrauch ist hoch." },
      { id: "ablesen", mot: "ablesen", pl: "—", fr: "relever (un compteur)", ex: "Der Techniker liest den Zähler ab." },
      { id: "zeuge", mot: "der Zeuge", pl: "die Zeugen", fr: "le témoin", ex: "Wir brauchen einen Zeugen für den Vertrag." },
      { id: "unterschreiben-logement", mot: "unterschreiben", pl: "—", fr: "signer", ex: "Wir unterschreiben den Mietvertrag." },
      { id: "klausel", mot: "die Klausel", pl: "die Klauseln", fr: "la clause", ex: "Diese Klausel ist wichtig." },
      { id: "absatz", mot: "der Absatz", pl: "die Absätze", fr: "le paragraphe (contrat)", ex: "Lesen Sie den Absatz sorgfältig." },
      { id: "bedingung", mot: "die Bedingung", pl: "die Bedingungen", fr: "la condition (contrat)", ex: "Die Bedingungen sind klar." },
      { id: "akzeptieren", mot: "akzeptieren", pl: "—", fr: "accepter", ex: "Ich akzeptiere die Bedingungen." },
      { id: "ablehnen", mot: "ablehnen", pl: "—", fr: "refuser", ex: "Der Vermieter lehnt den Antrag ab." },
      { id: "antrag-logement", mot: "der Antrag", pl: "die Anträge", fr: "la demande", ex: "Ich stelle einen Antrag auf Wohngeld." },
      { id: "wohngeld", mot: "das Wohngeld", pl: "—", fr: "l'allocation logement", ex: "Ich beantrage Wohngeld." },
      { id: "sozialwohnung", mot: "die Sozialwohnung", pl: "die Sozialwohnungen", fr: "le logement social", ex: "Sie wohnt in einer Sozialwohnung." },
      { id: "gemeinsam", mot: "gemeinsam", pl: "—", fr: "ensemble (partagé)", ex: "Wir teilen die Wohnung gemeinsam." },
      { id: "teilen", mot: "teilen", pl: "—", fr: "partager", ex: "Wir teilen die Miete." },
      { id: "wg-zimmer", mot: "das WG-Zimmer", pl: "die WG-Zimmer", fr: "la chambre en colocation", ex: "Ich suche ein WG-Zimmer." },
      { id: "umzugstermin", mot: "der Umzugstermin", pl: "die Umzugstermine", fr: "la date de déménagement", ex: "Der Umzugstermin steht fest." },
      { id: "sich-niederlassen", mot: "sich niederlassen", pl: "—", fr: "s'installer (définitivement)", ex: "Wir lassen uns hier nieder." },
    ],
  },
  {
    id: "universite-formation", label: "Université & formation", icone: "🎓",
    mots: [
      { id: "hochschule", mot: "die Hochschule", pl: "die Hochschulen", fr: "l'établissement d'enseignement supérieur", ex: "Er studiert an einer Hochschule." },
      { id: "fakultaet", mot: "die Fakultät", pl: "die Fakultäten", fr: "la faculté", ex: "Sie studiert an der medizinischen Fakultät." },
      { id: "studiengang", mot: "der Studiengang", pl: "die Studiengänge", fr: "la filière d'études", ex: "Der Studiengang dauert drei Jahre." },
      { id: "fachgebiet", mot: "das Fachgebiet", pl: "die Fachgebiete", fr: "le domaine d'études", ex: "Mein Fachgebiet ist Informatik." },
      { id: "vorlesung", mot: "die Vorlesung", pl: "die Vorlesungen", fr: "le cours magistral", ex: "Die Vorlesung beginnt um zehn Uhr." },
      { id: "seminar", mot: "das Seminar", pl: "die Seminare", fr: "le séminaire", ex: "Ich nehme an einem Seminar teil." },
      { id: "hausarbeit", mot: "die Hausarbeit", pl: "die Hausarbeiten", fr: "le devoir écrit (universitaire)", ex: "Ich schreibe eine Hausarbeit." },
      { id: "abschlussarbeit", mot: "die Abschlussarbeit", pl: "die Abschlussarbeiten", fr: "le mémoire de fin d'études", ex: "Meine Abschlussarbeit ist fast fertig." },
      { id: "bachelor", mot: "der Bachelor", pl: "die Bachelor", fr: "la licence (diplôme)", ex: "Ich mache meinen Bachelor." },
      { id: "master", mot: "der Master", pl: "die Master", fr: "le master", ex: "Sie studiert für ihren Master." },
      { id: "doktortitel", mot: "der Doktortitel", pl: "die Doktortitel", fr: "le doctorat", ex: "Er hat einen Doktortitel." },
      { id: "vorlesungszeit", mot: "die Vorlesungszeit", pl: "—", fr: "la période de cours", ex: "Die Vorlesungszeit beginnt im Oktober." },
      { id: "studium", mot: "das Studium", pl: "die Studien", fr: "les études (supérieures)", ex: "Das Studium ist anstrengend." },
      { id: "studienplatz", mot: "der Studienplatz", pl: "die Studienplätze", fr: "la place d'études", ex: "Ich habe einen Studienplatz bekommen." },
      { id: "sich-bewerben", mot: "sich bewerben", pl: "—", fr: "postuler", ex: "Ich bewerbe mich um einen Studienplatz." },
      { id: "bewerbung", mot: "die Bewerbung", pl: "die Bewerbungen", fr: "la candidature", ex: "Meine Bewerbung ist abgeschickt." },
      { id: "zulassung", mot: "die Zulassung", pl: "die Zulassungen", fr: "l'admission", ex: "Ich habe die Zulassung erhalten." },
      { id: "stipendium", mot: "das Stipendium", pl: "die Stipendien", fr: "la bourse (études)", ex: "Sie bekommt ein Stipendium." },
      { id: "studiengebuehren", mot: "die Studiengebühren", pl: "—", fr: "les frais de scolarité", ex: "Die Studiengebühren sind hoch." },
      { id: "klausur", mot: "die Klausur", pl: "die Klausuren", fr: "le contrôle écrit (partiel)", ex: "Die Klausur ist nächste Woche." },
      { id: "studienabschluss", mot: "der Studienabschluss", pl: "die Studienabschlüsse", fr: "le diplôme final", ex: "Der Studienabschluss dauert drei Jahre." },
      { id: "dozent", mot: "der Dozent", pl: "die Dozenten", fr: "le maître de conférences", ex: "Der Dozent erklärt das Thema gut." },
      { id: "professor", mot: "der Professor", pl: "die Professoren", fr: "le professeur (université)", ex: "Der Professor hält eine Vorlesung." },
      { id: "professorin", mot: "die Professorin", pl: "die Professorinnen", fr: "la professeure", ex: "Die Professorin forscht viel." },
      { id: "forschung", mot: "die Forschung", pl: "die Forschungen", fr: "la recherche (scientifique)", ex: "Die Forschung dauert Jahre." },
      { id: "forschen", mot: "forschen", pl: "—", fr: "faire de la recherche", ex: "Sie forscht im Labor." },
      { id: "labor", mot: "das Labor", pl: "die Labore", fr: "le laboratoire", ex: "Wir arbeiten im Labor." },
      { id: "praktikant", mot: "der Praktikant", pl: "die Praktikanten", fr: "le stagiaire", ex: "Der Praktikant lernt viel." },
      { id: "praktikum", mot: "das Praktikum", pl: "die Praktika", fr: "le stage", ex: "Ich mache ein Praktikum." },
      { id: "weiterbildung", mot: "die Weiterbildung", pl: "die Weiterbildungen", fr: "la formation continue", ex: "Ich mache eine Weiterbildung." },
      { id: "ausbildung", mot: "die Ausbildung", pl: "die Ausbildungen", fr: "la formation professionnelle", ex: "Er macht eine Ausbildung als Elektriker." },
      { id: "auszubildende", mot: "der Auszubildende", pl: "die Auszubildenden", fr: "l'apprenti", ex: "Der Auszubildende lernt im Betrieb." },
      { id: "berufsschule", mot: "die Berufsschule", pl: "die Berufsschulen", fr: "l'école professionnelle", ex: "Er geht zur Berufsschule." },
      { id: "betrieb", mot: "der Betrieb", pl: "die Betriebe", fr: "l'entreprise (formation)", ex: "Die Ausbildung findet im Betrieb statt." },
      { id: "fortbildung", mot: "die Fortbildung", pl: "die Fortbildungen", fr: "le perfectionnement professionnel", ex: "Ich mache eine Fortbildung." },
      { id: "fernstudium", mot: "das Fernstudium", pl: "die Fernstudien", fr: "les études à distance", ex: "Ich mache ein Fernstudium." },
      { id: "online-lernen", mot: "online lernen", pl: "—", fr: "apprendre en ligne", ex: "Ich lerne oft online." },
      { id: "plattform", mot: "die Plattform", pl: "die Plattformen", fr: "la plateforme (en ligne)", ex: "Die Lernplattform ist einfach." },
      { id: "kurs-formation", mot: "der Kurs", pl: "die Kurse", fr: "le cours (formation)", ex: "Ich mache einen Onlinekurs." },
      { id: "zertifikat", mot: "das Zertifikat", pl: "die Zertifikate", fr: "le certificat (formation)", ex: "Ich habe ein Zertifikat bekommen." },
      { id: "anerkennung", mot: "die Anerkennung", pl: "die Anerkennungen", fr: "la reconnaissance (diplôme)", ex: "Die Anerkennung meines Diploms dauert lange." },
      { id: "anerkennen", mot: "anerkennen", pl: "—", fr: "reconnaître (un diplôme)", ex: "Deutschland erkennt mein Diplom an." },
      { id: "qualifikation", mot: "die Qualifikation", pl: "die Qualifikationen", fr: "la qualification", ex: "Meine Qualifikation passt zur Stelle." },
      { id: "qualifiziert", mot: "qualifiziert", pl: "—", fr: "qualifié", ex: "Sie ist gut qualifiziert." },
      { id: "kompetenz", mot: "die Kompetenz", pl: "die Kompetenzen", fr: "la compétence", ex: "Er hat viele Kompetenzen." },
      { id: "faehigkeit", mot: "die Fähigkeit", pl: "die Fähigkeiten", fr: "la capacité", ex: "Diese Fähigkeit ist wichtig." },
      { id: "lebenslauf", mot: "der Lebenslauf", pl: "die Lebensläufe", fr: "le CV", ex: "Ich aktualisiere meinen Lebenslauf." },
      { id: "motivationsschreiben", mot: "das Motivationsschreiben", pl: "die Motivationsschreiben", fr: "la lettre de motivation", ex: "Ich schreibe ein Motivationsschreiben." },
      { id: "anschreiben", mot: "das Anschreiben", pl: "die Anschreiben", fr: "la lettre de candidature", ex: "Das Anschreiben ist wichtig." },
      { id: "unterlagen", mot: "die Unterlagen", pl: "—", fr: "les documents (dossier)", ex: "Ich schicke meine Unterlagen." },
      { id: "zeugnis-formation", mot: "das Zeugnis", pl: "die Zeugnisse", fr: "le bulletin", ex: "Mein Zeugnis ist sehr gut." },
      { id: "note-formation", mot: "die Note", pl: "die Noten", fr: "la note", ex: "Ich habe eine gute Note bekommen." },
      { id: "notendurchschnitt", mot: "der Notendurchschnitt", pl: "—", fr: "la moyenne (des notes)", ex: "Mein Notendurchschnitt ist gut." },
      { id: "bestehen", mot: "bestehen", pl: "—", fr: "réussir (un examen)", ex: "Ich habe die Prüfung bestanden." },
      { id: "durchfallen", mot: "durchfallen", pl: "—", fr: "échouer (un examen)", ex: "Er ist durch die Prüfung gefallen." },
      { id: "wiederholen-formation", mot: "wiederholen", pl: "—", fr: "redoubler", ex: "Ich muss die Klausur wiederholen." },
      { id: "fachrichtung", mot: "die Fachrichtung", pl: "die Fachrichtungen", fr: "la spécialisation", ex: "Meine Fachrichtung ist Wirtschaft." },
      { id: "sich-spezialisieren", mot: "sich spezialisieren", pl: "—", fr: "se spécialiser", ex: "Ich spezialisiere mich auf Pflege." },
      { id: "spezialisierung", mot: "die Spezialisierung", pl: "die Spezialisierungen", fr: "la spécialisation (statut)", ex: "Die Spezialisierung dauert zwei Jahre." },
      { id: "fachwissen", mot: "das Fachwissen", pl: "—", fr: "les connaissances spécialisées", ex: "Er hat viel Fachwissen." },
      { id: "vortrag", mot: "der Vortrag", pl: "die Vorträge", fr: "l'exposé", ex: "Ich halte einen Vortrag." },
      { id: "praesentieren", mot: "präsentieren", pl: "—", fr: "présenter (exposé)", ex: "Ich präsentiere mein Projekt." },
      { id: "praesentation", mot: "die Präsentation", pl: "die Präsentationen", fr: "la présentation", ex: "Die Präsentation war überzeugend." },
      { id: "referat", mot: "das Referat", pl: "die Referate", fr: "l'exposé (oral scolaire)", ex: "Ich halte ein Referat." },
      { id: "gruppenarbeit", mot: "die Gruppenarbeit", pl: "die Gruppenarbeiten", fr: "le travail de groupe", ex: "Wir machen eine Gruppenarbeit." },
      { id: "zusammenarbeiten", mot: "zusammenarbeiten", pl: "—", fr: "collaborer", ex: "Wir arbeiten gut zusammen." },
      { id: "austausch", mot: "der Austausch", pl: "die Austausche", fr: "l'échange (académique)", ex: "Ich mache ein Austauschsemester." },
      { id: "auslandssemester", mot: "das Auslandssemester", pl: "die Auslandssemester", fr: "le semestre à l'étranger", ex: "Ich mache ein Auslandssemester in Deutschland." },
      { id: "immatrikulation", mot: "die Immatrikulation", pl: "die Immatrikulationen", fr: "l'inscription universitaire", ex: "Die Immatrikulation ist online möglich." },
      { id: "sich-immatrikulieren", mot: "sich immatrikulieren", pl: "—", fr: "s'inscrire (université)", ex: "Ich immatrikuliere mich im September." },
    ],
  },
  {
    id: "travail-collegues", label: "Travail & collègues", icone: "💼",
    mots: [
      { id: "arbeitsplatz", mot: "der Arbeitsplatz", pl: "die Arbeitsplätze", fr: "le poste de travail", ex: "Mein Arbeitsplatz ist ruhig." },
      { id: "firma", mot: "die Firma", pl: "die Firmen", fr: "l'entreprise", ex: "Die Firma hat hundert Mitarbeiter." },
      { id: "unternehmen", mot: "das Unternehmen", pl: "die Unternehmen", fr: "l'entreprise (formel)", ex: "Das Unternehmen wächst schnell." },
      { id: "mitarbeiter", mot: "der Mitarbeiter", pl: "die Mitarbeiter", fr: "l'employé", ex: "Die Mitarbeiter sind zufrieden." },
      { id: "mitarbeiterin", mot: "die Mitarbeiterin", pl: "die Mitarbeiterinnen", fr: "l'employée", ex: "Die Mitarbeiterin arbeitet im Büro." },
      { id: "kollege-travail", mot: "der Kollege", pl: "die Kollegen", fr: "le collègue", ex: "Mein Kollege hilft mir oft." },
      { id: "kollegin", mot: "die Kollegin", pl: "die Kolleginnen", fr: "la collègue", ex: "Meine Kollegin ist sehr kompetent." },
      { id: "chef-travail", mot: "der Chef", pl: "die Chefs", fr: "le chef", ex: "Mein Chef ist streng." },
      { id: "chefin", mot: "die Chefin", pl: "die Chefinnen", fr: "la cheffe", ex: "Die Chefin lobt mein Team." },
      { id: "vorgesetzte", mot: "der Vorgesetzte", pl: "die Vorgesetzten", fr: "le supérieur hiérarchique", ex: "Mein Vorgesetzter ist fair." },
      { id: "abteilung-travail", mot: "die Abteilung", pl: "die Abteilungen", fr: "le service (entreprise)", ex: "Ich arbeite in der Personalabteilung." },
      { id: "personalabteilung", mot: "die Personalabteilung", pl: "—", fr: "le service des ressources humaines", ex: "Die Personalabteilung sucht neue Mitarbeiter." },
      { id: "buero", mot: "das Büro", pl: "die Büros", fr: "le bureau (lieu)", ex: "Mein Büro ist im dritten Stock." },
      { id: "team-travail", mot: "das Team", pl: "die Teams", fr: "l'équipe", ex: "Unser Team arbeitet gut zusammen." },
      { id: "meeting", mot: "das Meeting", pl: "die Meetings", fr: "la réunion", ex: "Das Meeting dauert eine Stunde." },
      { id: "besprechung", mot: "die Besprechung", pl: "die Besprechungen", fr: "la réunion (formelle)", ex: "Die Besprechung beginnt pünktlich." },
      { id: "termin-travail", mot: "der Termin", pl: "die Termine", fr: "le rendez-vous professionnel", ex: "Ich habe einen Termin mit einem Kunden." },
      { id: "aufgabe-travail", mot: "die Aufgabe", pl: "die Aufgaben", fr: "la tâche", ex: "Meine Aufgabe ist klar definiert." },
      { id: "projekt", mot: "das Projekt", pl: "die Projekte", fr: "le projet", ex: "Das Projekt läuft gut." },
      { id: "frist-travail", mot: "die Frist", pl: "die Fristen", fr: "le délai", ex: "Die Frist ist morgen." },
      { id: "arbeitsvertrag", mot: "der Arbeitsvertrag", pl: "die Arbeitsverträge", fr: "le contrat de travail", ex: "Der Arbeitsvertrag ist befristet." },
      { id: "befristet", mot: "befristet", pl: "—", fr: "à durée déterminée", ex: "Mein Vertrag ist befristet." },
      { id: "unbefristet", mot: "unbefristet", pl: "—", fr: "à durée indéterminée", ex: "Ich habe einen unbefristeten Vertrag." },
      { id: "probezeit", mot: "die Probezeit", pl: "die Probezeiten", fr: "la période d'essai", ex: "Die Probezeit dauert sechs Monate." },
      { id: "gehalt", mot: "das Gehalt", pl: "die Gehälter", fr: "le salaire", ex: "Mein Gehalt ist angemessen." },
      { id: "lohn", mot: "der Lohn", pl: "die Löhne", fr: "le salaire (horaire/ouvrier)", ex: "Der Lohn wird monatlich gezahlt." },
      { id: "gehaltserhoehung", mot: "die Gehaltserhöhung", pl: "die Gehaltserhöhungen", fr: "l'augmentation de salaire", ex: "Ich bekomme eine Gehaltserhöhung." },
      { id: "ueberstunde", mot: "die Überstunde", pl: "die Überstunden", fr: "l'heure supplémentaire", ex: "Ich mache oft Überstunden." },
      { id: "urlaub", mot: "der Urlaub", pl: "die Urlaube", fr: "les congés", ex: "Ich nehme drei Wochen Urlaub." },
      { id: "urlaubstag", mot: "der Urlaubstag", pl: "die Urlaubstage", fr: "le jour de congé", ex: "Mir bleiben noch zehn Urlaubstage." },
      { id: "krankschreiben", mot: "krankschreiben", pl: "—", fr: "mettre en arrêt maladie", ex: "Der Arzt hat mich krankgeschrieben." },
      { id: "krankschreibung", mot: "die Krankschreibung", pl: "die Krankschreibungen", fr: "l'arrêt maladie", ex: "Ich reiche meine Krankschreibung ein." },
      { id: "kuendigung-travail", mot: "die Kündigung", pl: "die Kündigungen", fr: "le licenciement", ex: "Die Kündigung kam überraschend." },
      { id: "kuendigen-travail", mot: "kündigen", pl: "—", fr: "démissionner / licencier", ex: "Ich kündige meine Stelle." },
      { id: "entlassen", mot: "entlassen", pl: "—", fr: "licencier", ex: "Die Firma hat ihn entlassen." },
      { id: "entlassung", mot: "die Entlassung", pl: "die Entlassungen", fr: "le licenciement (acte)", ex: "Die Entlassung war unerwartet." },
      { id: "sich-bewerben-travail", mot: "sich bewerben", pl: "—", fr: "postuler (emploi)", ex: "Ich bewerbe mich um eine Stelle." },
      { id: "stelle", mot: "die Stelle", pl: "die Stellen", fr: "le poste (emploi)", ex: "Die Stelle ist noch frei." },
      { id: "stellenanzeige", mot: "die Stellenanzeige", pl: "die Stellenanzeigen", fr: "l'offre d'emploi", ex: "Ich lese Stellenanzeigen." },
      { id: "vorstellungsgespraech", mot: "das Vorstellungsgespräch", pl: "die Vorstellungsgespräche", fr: "l'entretien d'embauche", ex: "Ich habe morgen ein Vorstellungsgespräch." },
      { id: "einstellen", mot: "einstellen", pl: "—", fr: "embaucher", ex: "Die Firma stellt neue Leute ein." },
      { id: "einstellung-emploi", mot: "die Einstellung", pl: "die Einstellungen", fr: "l'embauche", ex: "Die Einstellung erfolgt im Januar." },
      { id: "arbeitgeber", mot: "der Arbeitgeber", pl: "die Arbeitgeber", fr: "l'employeur", ex: "Mein Arbeitgeber ist zufrieden." },
      { id: "arbeitnehmer", mot: "der Arbeitnehmer", pl: "die Arbeitnehmer", fr: "le salarié", ex: "Die Arbeitnehmer haben Rechte." },
      { id: "arbeitszeit", mot: "die Arbeitszeit", pl: "die Arbeitszeiten", fr: "le temps de travail", ex: "Meine Arbeitszeit ist flexibel." },
      { id: "vollzeit", mot: "die Vollzeit", pl: "—", fr: "le temps plein", ex: "Ich arbeite Vollzeit." },
      { id: "teilzeit", mot: "die Teilzeit", pl: "—", fr: "le temps partiel", ex: "Sie arbeitet Teilzeit." },
      { id: "homeoffice", mot: "das Homeoffice", pl: "—", fr: "le télétravail", ex: "Ich arbeite oft im Homeoffice." },
      { id: "flexibel", mot: "flexibel", pl: "—", fr: "flexible", ex: "Meine Arbeitszeiten sind flexibel." },
      { id: "pause-travail", mot: "die Pause", pl: "die Pausen", fr: "la pause", ex: "Die Mittagspause dauert eine Stunde." },
      { id: "feierabend-travail", mot: "der Feierabend", pl: "—", fr: "la fin de journée", ex: "Endlich Feierabend!" },
      { id: "verantwortlich", mot: "verantwortlich", pl: "—", fr: "responsable", ex: "Ich bin für das Projekt verantwortlich." },
      { id: "verantwortung", mot: "die Verantwortung", pl: "die Verantwortungen", fr: "la responsabilité", ex: "Ich übernehme Verantwortung." },
      { id: "erfahrung-travail", mot: "die Erfahrung", pl: "die Erfahrungen", fr: "l'expérience (professionnelle)", ex: "Ich habe viel Erfahrung." },
      { id: "berufserfahrung", mot: "die Berufserfahrung", pl: "—", fr: "l'expérience professionnelle", ex: "Meine Berufserfahrung ist wichtig." },
      { id: "beruf-travail", mot: "der Beruf", pl: "die Berufe", fr: "la profession", ex: "Mein Beruf ist Krankenpfleger." },
      { id: "karriere", mot: "die Karriere", pl: "die Karrieren", fr: "la carrière", ex: "Sie macht eine gute Karriere." },
      { id: "befoerdern", mot: "befördern", pl: "—", fr: "promouvoir", ex: "Man hat ihn befördert." },
      { id: "befoerderung", mot: "die Beförderung", pl: "die Beförderungen", fr: "la promotion", ex: "Ich bekomme eine Beförderung." },
      { id: "zusammenarbeit", mot: "die Zusammenarbeit", pl: "—", fr: "la collaboration", ex: "Die Zusammenarbeit funktioniert gut." },
      { id: "leiten", mot: "leiten", pl: "—", fr: "diriger (une équipe)", ex: "Sie leitet ein großes Team." },
      { id: "leiter", mot: "der Leiter", pl: "die Leiter", fr: "le directeur", ex: "Der Leiter trifft die Entscheidungen." },
      { id: "leiterin", mot: "die Leiterin", pl: "die Leiterinnen", fr: "la directrice", ex: "Die Leiterin ist sehr kompetent." },
      { id: "entscheidung", mot: "die Entscheidung", pl: "die Entscheidungen", fr: "la décision", ex: "Wir treffen eine Entscheidung." },
      { id: "entscheiden", mot: "entscheiden", pl: "—", fr: "décider", ex: "Wir entscheiden gemeinsam." },
      { id: "sitzung", mot: "die Sitzung", pl: "die Sitzungen", fr: "la séance", ex: "Die Sitzung dauert lange." },
      { id: "bericht", mot: "der Bericht", pl: "die Berichte", fr: "le rapport (travail)", ex: "Ich schreibe einen Bericht." },
      { id: "berichten", mot: "berichten", pl: "—", fr: "rapporter (informer)", ex: "Ich berichte über den Fortschritt." },
      { id: "ziel", mot: "das Ziel", pl: "die Ziele", fr: "l'objectif", ex: "Unser Ziel ist klar." },
      { id: "erreichen", mot: "erreichen", pl: "—", fr: "atteindre (un objectif)", ex: "Wir erreichen unser Ziel." },
      { id: "leistung", mot: "die Leistung", pl: "die Leistungen", fr: "la performance", ex: "Seine Leistung ist ausgezeichnet." },
      { id: "leisten", mot: "leisten", pl: "—", fr: "accomplir", ex: "Wir leisten gute Arbeit." },
      { id: "motiviert", mot: "motiviert", pl: "—", fr: "motivé", ex: "Das Team ist sehr motiviert." },
      { id: "motivation", mot: "die Motivation", pl: "—", fr: "la motivation", ex: "Ihre Motivation ist beeindruckend." },
      { id: "stress-travail", mot: "der Stress", pl: "—", fr: "le stress", ex: "Der Job macht viel Stress." },
      { id: "belastung", mot: "die Belastung", pl: "die Belastungen", fr: "la charge (de travail)", ex: "Die Belastung ist hoch." },
      { id: "sich-erholen-travail", mot: "sich erholen", pl: "—", fr: "se reposer (du travail)", ex: "Ich erhole mich am Wochenende." },
      { id: "gruenden", mot: "gründen", pl: "—", fr: "fonder (une entreprise)", ex: "Er gründet eine Firma." },
      { id: "gruender", mot: "der Gründer", pl: "die Gründer", fr: "le fondateur", ex: "Der Gründer ist erfolgreich." },
      { id: "startup", mot: "das Startup", pl: "die Startups", fr: "la start-up", ex: "Sie arbeitet in einem Startup." },
      { id: "selbststaendige", mot: "der Selbstständige", pl: "die Selbstständigen", fr: "l'indépendant", ex: "Er ist selbstständig." },
      { id: "selbststaendig", mot: "selbstständig", pl: "—", fr: "indépendant (statut)", ex: "Sie arbeitet selbstständig." },
      { id: "freiberufler", mot: "der Freiberufler", pl: "die Freiberufler", fr: "le freelance", ex: "Ich bin Freiberufler." },
      { id: "steuer", mot: "die Steuer", pl: "die Steuern", fr: "l'impôt", ex: "Ich zahle meine Steuern." },
      { id: "rente", mot: "die Rente", pl: "die Renten", fr: "la retraite", ex: "Er geht bald in Rente." },
      { id: "in-rente-gehen", mot: "in Rente gehen", pl: "—", fr: "partir à la retraite", ex: "Sie geht nächstes Jahr in Rente." },
      { id: "ruhestand", mot: "der Ruhestand", pl: "—", fr: "la retraite (statut)", ex: "Er genießt den Ruhestand." },
      { id: "gewerkschaft", mot: "die Gewerkschaft", pl: "die Gewerkschaften", fr: "le syndicat", ex: "Die Gewerkschaft vertritt die Arbeitnehmer." },
      { id: "betriebsrat", mot: "der Betriebsrat", pl: "die Betriebsräte", fr: "le comité d'entreprise", ex: "Der Betriebsrat trifft sich monatlich." },
      { id: "streiken", mot: "streiken", pl: "—", fr: "faire grève", ex: "Die Mitarbeiter streiken." },
      { id: "streik", mot: "der Streik", pl: "die Streiks", fr: "la grève", ex: "Der Streik dauert eine Woche." },
      { id: "arbeitsamt", mot: "das Arbeitsamt", pl: "die Arbeitsämter", fr: "le pôle emploi", ex: "Ich gehe zum Arbeitsamt." },
      { id: "arbeitslos", mot: "arbeitslos", pl: "—", fr: "au chômage", ex: "Er ist seit einem Monat arbeitslos." },
      { id: "arbeitslosigkeit", mot: "die Arbeitslosigkeit", pl: "—", fr: "le chômage", ex: "Die Arbeitslosigkeit ist gesunken." },
      { id: "arbeitslosengeld", mot: "das Arbeitslosengeld", pl: "—", fr: "les allocations chômage", ex: "Ich bekomme Arbeitslosengeld." },
      { id: "arbeitsalltag", mot: "der Arbeitsalltag", pl: "—", fr: "le quotidien professionnel", ex: "Mein Arbeitsalltag ist abwechslungsreich." },
      { id: "firmenkultur", mot: "die Firmenkultur", pl: "—", fr: "la culture d'entreprise", ex: "Die Firmenkultur gefällt mir." },
      { id: "betriebsklima", mot: "das Betriebsklima", pl: "—", fr: "l'ambiance de travail", ex: "Das Betriebsklima ist gut." },
      { id: "sich-wohlfuehlen-travail", mot: "sich wohlfühlen", pl: "—", fr: "se sentir bien (au travail)", ex: "Ich fühle mich hier wohl." },
    ],
  },
  {
    id: "voiture-circulation", label: "Voiture & circulation", icone: "🚗",
    mots: [
      { id: "auto-voiture", mot: "das Auto", pl: "die Autos", fr: "la voiture", ex: "Mein Auto ist in der Werkstatt." },
      { id: "wagen", mot: "der Wagen", pl: "die Wagen", fr: "la voiture (synonyme)", ex: "Der Wagen ist neu." },
      { id: "motor", mot: "der Motor", pl: "die Motoren", fr: "le moteur", ex: "Der Motor macht ein komisches Geräusch." },
      { id: "lenkrad", mot: "das Lenkrad", pl: "die Lenkräder", fr: "le volant", ex: "Das Lenkrad vibriert." },
      { id: "bremse", mot: "die Bremse", pl: "die Bremsen", fr: "le frein", ex: "Die Bremsen quietschen." },
      { id: "bremsen", mot: "bremsen", pl: "—", fr: "freiner", ex: "Ich bremse langsam." },
      { id: "gaspedal", mot: "das Gaspedal", pl: "die Gaspedale", fr: "la pédale d'accélérateur", ex: "Er tritt auf das Gaspedal." },
      { id: "reifen", mot: "der Reifen", pl: "die Reifen", fr: "le pneu", ex: "Der Reifen ist platt." },
      { id: "windschutzscheibe", mot: "die Windschutzscheibe", pl: "die Windschutzscheiben", fr: "le pare-brise", ex: "Die Windschutzscheibe ist zersprungen." },
      { id: "kofferraum", mot: "der Kofferraum", pl: "die Kofferräume", fr: "le coffre", ex: "Der Kofferraum ist voll." },
      { id: "motorhaube", mot: "die Motorhaube", pl: "die Motorhauben", fr: "le capot", ex: "Die Motorhaube ist offen." },
      { id: "blinker", mot: "der Blinker", pl: "die Blinker", fr: "le clignotant", ex: "Setz den Blinker!" },
      { id: "nummernschild", mot: "das Nummernschild", pl: "die Nummernschilder", fr: "la plaque d'immatriculation", ex: "Das Nummernschild ist schmutzig." },
      { id: "werkstatt", mot: "die Werkstatt", pl: "die Werkstätten", fr: "le garage (atelier)", ex: "Das Auto ist in der Werkstatt." },
      { id: "reparieren-voiture", mot: "reparieren", pl: "—", fr: "réparer", ex: "Der Mechaniker repariert das Auto." },
      { id: "mechaniker", mot: "der Mechaniker", pl: "die Mechaniker", fr: "le mécanicien", ex: "Der Mechaniker prüft den Motor." },
      { id: "reparatur", mot: "die Reparatur", pl: "die Reparaturen", fr: "la réparation", ex: "Die Reparatur kostet viel." },
      { id: "tuev", mot: "der TÜV", pl: "—", fr: "le contrôle technique", ex: "Der TÜV steht bald an." },
      { id: "versicherung", mot: "die Versicherung", pl: "die Versicherungen", fr: "l'assurance", ex: "Meine Versicherung deckt den Schaden." },
      { id: "unfall", mot: "der Unfall", pl: "die Unfälle", fr: "l'accident", ex: "Es gab einen Unfall." },
      { id: "panne", mot: "die Panne", pl: "die Pannen", fr: "la panne", ex: "Wir hatten eine Panne." },
      { id: "abschleppen", mot: "abschleppen", pl: "—", fr: "remorquer", ex: "Der Abschleppwagen kommt." },
      { id: "abschleppwagen", mot: "der Abschleppwagen", pl: "die Abschleppwagen", fr: "la dépanneuse", ex: "Der Abschleppwagen bringt das Auto zur Werkstatt." },
      { id: "geschwindigkeit", mot: "die Geschwindigkeit", pl: "die Geschwindigkeiten", fr: "la vitesse", ex: "Die Geschwindigkeit ist zu hoch." },
      { id: "tempolimit", mot: "das Tempolimit", pl: "die Tempolimits", fr: "la limitation de vitesse", ex: "Das Tempolimit ist hundert." },
      { id: "zu-schnell-fahren", mot: "zu schnell fahren", pl: "—", fr: "rouler trop vite", ex: "Er fährt zu schnell." },
      { id: "verkehrsregel", mot: "die Verkehrsregel", pl: "die Verkehrsregeln", fr: "la règle de circulation", ex: "Verkehrsregeln müssen beachtet werden." },
      { id: "verkehrsschild", mot: "das Verkehrsschild", pl: "die Verkehrsschilder", fr: "le panneau de signalisation", ex: "Das Verkehrsschild zeigt Stopp." },
      { id: "vorfahrt", mot: "die Vorfahrt", pl: "—", fr: "la priorité", ex: "Ich habe keine Vorfahrt." },
      { id: "ueberholen", mot: "überholen", pl: "—", fr: "doubler", ex: "Er überholt vorsichtig." },
      { id: "spur", mot: "die Spur", pl: "die Spuren", fr: "la voie (route)", ex: "Bleib auf deiner Spur." },
      { id: "kreuzung-voiture", mot: "die Kreuzung", pl: "die Kreuzungen", fr: "le carrefour", ex: "An der Kreuzung anhalten." },
      { id: "kreisverkehr", mot: "der Kreisverkehr", pl: "die Kreisverkehre", fr: "le rond-point", ex: "Am Kreisverkehr rechts abbiegen." },
      { id: "abbiegen", mot: "abbiegen", pl: "—", fr: "tourner (véhicule)", ex: "Ich biege links ab." },
      { id: "wenden", mot: "wenden", pl: "—", fr: "faire demi-tour", ex: "Ich kann hier nicht wenden." },
      { id: "rueckwaerts-fahren", mot: "rückwärts fahren", pl: "—", fr: "faire marche arrière", ex: "Er fährt rückwärts ein." },
      { id: "einparken", mot: "einparken", pl: "—", fr: "se garer (manœuvre)", ex: "Ich parke schwer ein." },
      { id: "parkschein", mot: "der Parkschein", pl: "die Parkscheine", fr: "le ticket de parking", ex: "Kauf einen Parkschein." },
      { id: "strafzettel", mot: "der Strafzettel", pl: "die Strafzettel", fr: "la contravention", ex: "Ich habe einen Strafzettel bekommen." },
      { id: "geldstrafe", mot: "die Geldstrafe", pl: "die Geldstrafen", fr: "l'amende", ex: "Die Geldstrafe ist hoch." },
      { id: "ampel-voiture", mot: "die Ampel", pl: "die Ampeln", fr: "le feu", ex: "Die Ampel ist grün." },
      { id: "fuehrerschein-voiture", mot: "der Führerschein", pl: "die Führerscheine", fr: "le permis de conduire", ex: "Ich habe meinen Führerschein bestanden." },
      { id: "fahrschule", mot: "die Fahrschule", pl: "die Fahrschulen", fr: "l'auto-école", ex: "Ich gehe zur Fahrschule." },
      { id: "fahrlehrer", mot: "der Fahrlehrer", pl: "die Fahrlehrer", fr: "le moniteur d'auto-école", ex: "Der Fahrlehrer ist geduldig." },
      { id: "fahrpruefung", mot: "die Fahrprüfung", pl: "die Fahrprüfungen", fr: "l'examen de conduite", ex: "Ich habe die Fahrprüfung bestanden." },
      { id: "benzin-voiture", mot: "das Benzin", pl: "—", fr: "l'essence", ex: "Das Benzin ist teuer geworden." },
      { id: "tankstelle", mot: "die Tankstelle", pl: "die Tankstellen", fr: "la station-service", ex: "Wir halten an der Tankstelle." },
      { id: "voll-tanken", mot: "voll tanken", pl: "—", fr: "faire le plein", ex: "Ich tanke voll." },
      { id: "diesel", mot: "der Diesel", pl: "—", fr: "le diesel", ex: "Mein Auto fährt mit Diesel." },
      { id: "elektroauto", mot: "das Elektroauto", pl: "die Elektroautos", fr: "la voiture électrique", ex: "Wir kaufen ein Elektroauto." },
      { id: "ladestation", mot: "die Ladestation", pl: "die Ladestationen", fr: "la borne de recharge", ex: "Die Ladestation ist frei." },
      { id: "aufladen", mot: "aufladen", pl: "—", fr: "recharger (électrique)", ex: "Ich lade mein Auto auf." },
      { id: "stau-voiture", mot: "der Stau", pl: "die Staus", fr: "l'embouteillage", ex: "Wir stecken im Stau." },
      { id: "baustelle", mot: "die Baustelle", pl: "die Baustellen", fr: "le chantier (route)", ex: "Es gibt eine Baustelle auf der Autobahn." },
      { id: "umleitung", mot: "die Umleitung", pl: "die Umleitungen", fr: "la déviation", ex: "Es gibt eine Umleitung." },
      { id: "verkehr", mot: "der Verkehr", pl: "—", fr: "le trafic", ex: "Der Verkehr ist stark." },
      { id: "stosszeit", mot: "die Stoßzeit", pl: "die Stoßzeiten", fr: "l'heure de pointe", ex: "Zur Stoßzeit ist viel Verkehr." },
      { id: "hupen", mot: "hupen", pl: "—", fr: "klaxonner", ex: "Der Fahrer hupt." },
      { id: "hupe", mot: "die Hupe", pl: "die Hupen", fr: "le klaxon", ex: "Die Hupe ist laut." },
      { id: "autobahnauffahrt", mot: "die Autobahnauffahrt", pl: "die Autobahnauffahrten", fr: "la bretelle d'accès autoroute", ex: "Die Autobahnauffahrt ist gesperrt." },
      { id: "ausfahrt", mot: "die Ausfahrt", pl: "die Ausfahrten", fr: "la sortie (autoroute)", ex: "Nimm die nächste Ausfahrt." },
      { id: "maut", mot: "die Maut", pl: "die Mauten", fr: "le péage", ex: "Die Maut kostet zehn Euro." },
      { id: "navigationsgeraet", mot: "das Navigationsgerät", pl: "die Navigationsgeräte", fr: "le GPS", ex: "Das Navigationsgerät zeigt den Weg." },
      { id: "route", mot: "die Route", pl: "die Routen", fr: "l'itinéraire", ex: "Die Route ist schneller." },
      { id: "anhaenger", mot: "der Anhänger", pl: "die Anhänger", fr: "la remorque", ex: "Wir ziehen einen Anhänger." },
      { id: "beifahrer", mot: "der Beifahrer", pl: "die Beifahrer", fr: "le passager avant", ex: "Mein Beifahrer navigiert." },
      { id: "mitfahren", mot: "mitfahren", pl: "—", fr: "covoiturer", ex: "Ich fahre mit ihm mit." },
      { id: "fahrgemeinschaft", mot: "die Fahrgemeinschaft", pl: "die Fahrgemeinschaften", fr: "le covoiturage", ex: "Wir bilden eine Fahrgemeinschaft." },
      { id: "gebrauchtwagen", mot: "der Gebrauchtwagen", pl: "die Gebrauchtwagen", fr: "la voiture d'occasion", ex: "Ich kaufe einen Gebrauchtwagen." },
      { id: "neuwagen", mot: "der Neuwagen", pl: "die Neuwagen", fr: "la voiture neuve", ex: "Ein Neuwagen ist teuer." },
    ],
  },
];
